#debug: true
jasypt:
  encryptor:
    password: ${ENCRYPTION_SECRET_KEY}  # pass this via environment variable or JVM arg
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    provider-class-name: org.bouncycastle.jce.provider.BouncyCastleProvider
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/algotrading?currentSchema=algo_dev
    username: algotradinguser
    password: ENC(xMcc+WJjFdgEA1Vsqs+We0PHCB6URFr9M7Wd2mqA1WKjfJjzuuxJFdqnKfff46cZFkmH1nntlCSf9V9+5ovQlg==)
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: algo_dev  # Optional: if you're using a non-default schema
    drop-first: false            # true if you want to drop and re-create DB on each run (careful!)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
kite:
  api-key: ENC(l8uI0WMqy+3zzn7MEVLiYw064bBlVnqprKwdx17Kh3O0Q0CO4b9oeGbZblLlDdbWBvxqGRyrsfW6A9I70ry+uw==)
  api-secret: ENC(r8Vzbu7kjL2V7qmRQsPskWccZapm3JuA8x2xnTOFgn62ss+fIClRoC0Vs+m6TI25fN31sLRUrDuCaX1YfW+/MJ9aodHakqzQTt/II6vatos=)
  login-url: https://kite.zerodha.com/connect/login?v=3&api_key=
  trade-url: https://api.kite.trade
  user-id: QG2526
logging:
  level:
    com:
      example:
        algotrading: INFO
  file:
    name: logs/algotrading.log  # Path to your log file
live:
  holdings:
    websocket:
      enabled: false